# RENAME FILE TO 'config.yml'
bot:
  token: TOKEN FROM DISCORD
  owner_ids:
    - 1381458834949672960
  prefix: svg
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
